//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cases
    {
        public int Id { get; set; }
        public string Municipal { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> Recovered { get; set; }
        public Nullable<int> Death { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
