//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients
    {
        public int Id { get; set; }
        public Nullable<int> BatchId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> CivilStatus { get; set; }
        public Nullable<int> Nationality { get; set; }
        public Nullable<int> Mobile { get; set; }
        public Nullable<int> CurrentProvince { get; set; }
        public Nullable<int> CurrentMunicipality { get; set; }
        public Nullable<int> CurrentBarangay { get; set; }
        public string CurrentStreet { get; set; }
        public Nullable<int> PermanentProvince { get; set; }
        public Nullable<int> PermanentMunicipality { get; set; }
        public Nullable<int> PermanentBarangay { get; set; }
        public string PermanentStreet { get; set; }
    
        public virtual BatchNumbers BatchNumbers { get; set; }
    }
}
