//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residents
    {
        public string CaseID { get; set; }
        public string BatchID { get; set; }
        public string CovidKayaID { get; set; }
        public string PhilhealthNumber { get; set; }
        public string PHNo { get; set; }
        public string CVNo { get; set; }
        public string LabResultID { get; set; }
        public string FacilityName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string SuffixID { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
        public string SexID { get; set; }
        public string CivilStatusID { get; set; }
        public string Nationality { get; set; }
        public string CurrentStreet { get; set; }
        public string CurrentRegionID { get; set; }
        public string CurrentProvinceID { get; set; }
        public string CurrentCityMunicipalityID { get; set; }
        public string CurrentBarangayID { get; set; }
        public string CurrentMobile { get; set; }
        public string PermanentStreet { get; set; }
        public string PermanentRegionID { get; set; }
        public string PermanentProvinceID { get; set; }
        public string PermanentCityMunicipalityID { get; set; }
        public string PermanentBarangayID { get; set; }
        public string SpecialPopulationID { get; set; }
        public string HealthCareWorkerYN { get; set; }
        public string Occupation { get; set; }
        public string ExposureID { get; set; }
        public string CloseContactCVNumber { get; set; }
        public string SpecifyExposurePlace { get; set; }
        public string TravelHistoryWithCovid19YN { get; set; }
        public string DateArrivalMNL { get; set; }
        public string DateArrivalRES { get; set; }
        public string TravelHistory14Days { get; set; }
        public string TravelHistory14DaysDateFrom { get; set; }
        public string TravelHistory14DaysFromLocation { get; set; }
        public string TravelHistory14DaysDateTo { get; set; }
        public string TravelHistory14DaysToLocation { get; set; }
        public string DateOnset { get; set; }
        public string AdmittedYN { get; set; }
        public string AdmittingFacilityID { get; set; }
        public string CurrentHealthStatus { get; set; }
        public string DateConsulted { get; set; }
        public string DateAdmitted { get; set; }
        public string FeverYN { get; set; }
        public string CoughYN { get; set; }
        public string ColdYN { get; set; }
        public string SoreThroatYN { get; set; }
        public string RespiratoryInfectionYN { get; set; }
        public string DiarrheaYN { get; set; }
        public string OtherSymptomsYN { get; set; }
        public string SpecifySymptoms { get; set; }
        public string HypertensionYN { get; set; }
        public string DiabetesYN { get; set; }
        public string TuberculosisYN { get; set; }
        public string CancerYN { get; set; }
        public string RenalDiseaseYN { get; set; }
        public string CardiacDiseaseYN { get; set; }
        public string AutoimmuneDiseaseYN { get; set; }
        public string PregnantYN { get; set; }
        public string HighRiskPregnancyYN { get; set; }
        public string OtherConditionComorbidityYN { get; set; }
        public string SpecifyConditionComorbidity { get; set; }
        public string CaseClassificationID { get; set; }
        public string OutcomeID { get; set; }
        public string DateDischarged { get; set; }
        public string DateRecovered { get; set; }
        public string DateDied { get; set; }
        public string CauseOfDeath { get; set; }
        public string QuarantineYN { get; set; }
        public string PlaceOfQuarantine { get; set; }
        public string SpecifyQuarantineLocation { get; set; }
        public string Remarks { get; set; }
        public string LaboratoryTestID { get; set; }
        public string LaboratoryID { get; set; }
        public string LaboratoryTestSerialNo { get; set; }
        public string DateTimeSpecimenCollected { get; set; }
        public string DateTimeSpecimenSentToLab { get; set; }
        public string DateTimeReceivedInLab { get; set; }
        public string DateTimeReleaseOfResult { get; set; }
        public string AttendingPhysician { get; set; }
        public string SpecimenTypeID { get; set; }
        public string TestTypeID { get; set; }
    }
}
